### ISSUE TITLE
Could you tell me how to label those attributes on the image?(Which software did you use?)

### ISSUE THREAD

**Issue by Aaron5210** [vana77/Duke_Attribute#4]
.

**Comment by layumi** [comment]
We write a gui project in Matlab to annotate the images.

**Comment by layumi** [comment]
If you want to access the annotation data, you may use Matlab to read them.

**Comment by BabuTango** [comment]
@layumi I'm able to access the annotated data.
But I want to annotate my custom data, can you please tell how to annotate the new data. 
1. Which tool to use for annotation.
2. Can I add any new attributes or should I stick with the pre-defined attributes.

Thanks

**Comment by ayanasser** [comment]
@layumi  Hi ^^
I need an answer on this question too ^^
